drop table "public"."PERSISTENCEIMPL_LISTOFSTRINGS";
drop table "public"."PERSISTENCEIMPL_LISTOFINTERFACES";
drop table "public"."PERSISTENCEIMPL_HASHMAPOFSTRINGS";
drop table "public"."PERSISTENCEIMPL_HASHMAPOFINTERFACES";
drop table "public"."PERSISTENCEIMPL_HASHMAPOFIMPL";
drop table "public"."INTERFACEIMPL1";
drop table "public"."INTERFACEIMPL2";
drop table "public"."PERSISTENCEIMPL";

drop table "public"."DATANUCLEUSFLOWTRANSACTIONPERSISTENCE_LISTOFTRANSFORMERS";
drop table "public"."DATANUCLEUSFLOWTRANSACTIONPERSISTENCE_FLOWRUNNERSNAMES";
drop table "public"."DATANUCLEUSFLOWTRANSACTIONPERSISTENCE_FLOWRUNNERSINSTANCES";
drop table "public"."STAXONSIMPLEFLOWRUNNER";
drop table "public"."STATICFLOWRUNNER";
drop table "public"."DIGESTERFLOWRUNNER";
drop table "public"."DATANUCLEUSFLOWTRANSACTIONPERSISTENCE";